#!/usr/bin/env node
/**
 * Release Notes Generator
 * Użycie: node release-notes.mjs <tag>
 * Przykład: node release-notes.mjs uat-version-20260316185950
 *
 * Wymagane zmienne środowiskowe w pliku .env:
 *   GITHUB_TOKEN      – Personal Access Token (repo scope)
 *   JIRA_EMAIL        – email do Jira Cloud
 *   JIRA_API_TOKEN    – token Jira API
 *   JIRA_BASE_URL     – np. https://restaumatic.atlassian.net
 *   GOOGLE_DOC_ID     – ID dokumentu Google Docs (z URL)
 *   GOOGLE_SA_KEY     – ścieżka do pliku JSON z kluczem Service Account
 */

import { config } from "dotenv";
import fetch from "node-fetch";
import { google } from "googleapis";

config();

// ─── Konfiguracja ─────────────────────────────────────────────────────────────

const GITHUB_TOKEN   = process.env.GITHUB_TOKEN;
const JIRA_EMAIL     = process.env.JIRA_EMAIL;
const JIRA_API_TOKEN = process.env.JIRA_API_TOKEN;
const JIRA_BASE_URL  = process.env.JIRA_BASE_URL;
const GOOGLE_DOC_ID  = process.env.GOOGLE_DOC_ID;
const GOOGLE_SA_KEY    = process.env.GOOGLE_SA_KEY;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const GITHUB_OWNER = "restaumatic";
const GITHUB_REPO  = "restaumatic";

/** Mapa github_login (bez @, lowercase) → projekt */
const USER_PROJECT_MAP = {
  "pmlodawski":     "B2B",
  "obrebski":       "Billing",
  "mateuszbujalski":"B2B",
  "korrix":         "B2C",
  "erykciepiela":   "B2B",
  "zyla":           "Dev Tools",
  "kozak":          "Dev Tools",
  "alternateved":   "B2C",
  "sg-webdev":      "B2C",
  "pwegrzynski":    "B2C",
  "jborkowski":     "B2B",
  "damianwajer":    "B2C",
  "mikolajwaskowski": "B2C"
};

const PROJECT_ORDER = ["B2B", "B2C", "Billing", "Dev Tools", "Inne"];

// ─── GitHub API ───────────────────────────────────────────────────────────────

async function ghFetch(path) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}${path}`, {
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
    },
  });
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${path}`);
  return res.json();
}

async function getReleaseBody(tag) {
  const release = await ghFetch(`/releases/tags/${tag}`);
  return release.body ?? "";
}

async function getJiraKeyFromPR(prNumber) {
  const pr = await ghFetch(`/pulls/${prNumber}`);
  const text = `${pr.title ?? ""} ${pr.body ?? ""}`;
  const m = text.match(/\b([A-Z][A-Z0-9]+-\d+)\b/);
  return m ? m[1] : null;
}

// ─── Parser linii changelogu ──────────────────────────────────────────────────
// Format GitHub autogenerated changelog:
// "* Opis zmiany by @autor in #12405"

function parseLines(body) {
  const results = [];

  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line.startsWith("* ") && !line.startsWith("- ")) continue;
    const text = line.replace(/^[*-] /, "").trim();

    // Wyciągnij autora: "by @login in"
    const authorMatch = text.match(/by @([\w-]+)/i);
    const login = authorMatch ? authorMatch[1].toLowerCase() : null;

    // Wyciągnij numer PR: "in #12405" lub "in https://github.com/.../pull/12405"
    const prMatch = text.match(/in #(\d+)/i) ?? text.match(/pull\/(\d+)/i);
    const prNumber = prMatch ? prMatch[1] : null;

    // Wyciągnij klucz Jiry z opisu: RS-11221, B2C-1537 itp.
    const jiraMatch = text.match(/\b([A-Z][A-Z0-9]+-\d+)\b/);
    const jiraKey = jiraMatch ? jiraMatch[1] : null;

    // Wyczyść opis – usuń " by @autor in #PR" lub " by @autor in https://..."
    const description = text
      .replace(/\s+by @[\w-]+ in https?:\/\/\S+/i, "")
      .replace(/\s+by @[\w-]+ in #\d+/i, "")
      .trim();

    // Przypisz do projektu
    const project = login ? (USER_PROJECT_MAP[login] ?? "Inne") : "Inne";

    results.push({ description, login, prNumber, jiraKey, project });
  }

  return results;
}

// ─── Jira API ─────────────────────────────────────────────────────────────────

const jiraAuth = Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString("base64");

async function getJiraIssue(key) {
  const res = await fetch(`${JIRA_BASE_URL}/rest/api/3/issue/${key}?fields=summary,description`, {
    headers: {
      Authorization: `Basic ${jiraAuth}`,
      Accept: "application/json",
    },
  });
  if (!res.ok) {
    console.warn(`  ⚠ Jira ${key}: ${res.status} – pomijam`);
    return null;
  }
  const data = await res.json();
  return {
    summary:     data.fields?.summary ?? "",
    description: flattenADF(data.fields?.description).trim(),
    url:         `${JIRA_BASE_URL}/browse/${key}`,
  };
}

/** Spłaszcza Atlassian Document Format do czystego tekstu */
function flattenADF(node) {
  if (!node) return "";
  if (typeof node === "string") return node;
  if (node.type === "text") return node.text ?? "";
  if (Array.isArray(node.content)) return node.content.map(flattenADF).join(" ");
  return "";
}

// ─── Anthropic API ────────────────────────────────────────────────────────────

async function rewriteDescription(rawDesc, jiraTitle) {
  if (!rawDesc && !jiraTitle) return null;

  const input = rawDesc
    ? `Tytuł zadania: ${jiraTitle ?? ""}\nOpis: ${rawDesc}`
    : `Tytuł zadania: ${jiraTitle}`;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 150,
      system: `Jesteś asystentem piszącym krótkie opisy zmian w aplikacji dla wszystkich pracowników firmy.
Przepisuj opisy zmian po polsku, prostym językiem zrozumiałym dla osób nietechnicznych.
Odpowiadaj TYLKO opisem – 1-2 zdania, bez wstępu, bez cudzysłowów, bez formatowania.`,
      messages: [{ role: "user", content: input }],
    }),
  });

  if (!res.ok) {
    console.warn(`  ⚠ Anthropic API ${res.status} – zostawiam oryginalny opis`);
    return rawDesc;
  }

  const data = await res.json();
  return data.content?.[0]?.text?.trim() ?? rawDesc;
}



async function buildReleaseNotes(tag) {
  console.log(`\n🔍 Pobieranie release: ${tag}`);
  const body = await getReleaseBody(tag);

  if (!body || body.trim().length < 10) {
    throw new Error("Release jest pusty – brak treści do przetworzenia.");
  }

  const raw = parseLines(body);

  // Deduplikacja – ten sam PR może pojawić się wielokrotnie w changelog
  const seen = new Set();
  const entries = raw.filter(e => {
    const key = e.prNumber ?? e.description;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  console.log(`   Znaleziono ${raw.length} wpisów, po deduplikacji: ${entries.length}.\n`);

  // Grupuj po projekcie
  const sections = Object.fromEntries(PROJECT_ORDER.map(p => [p, []]));

  for (const entry of entries) {
    console.log(`  • [${entry.project}] ${entry.description.slice(0, 60)}...`);

    let jiraKey = entry.jiraKey;

    // Jeśli brak klucza Jiry w nazwie – sprawdź treść PR
    if (!jiraKey && entry.prNumber) {
      console.log(`    → PR #${entry.prNumber}: szukam linku do Jiry...`);
      jiraKey = await getJiraKeyFromPR(entry.prNumber);
      if (jiraKey) console.log(`       znaleziono: ${jiraKey}`);
    }

    let jira = null;
    if (jiraKey) {
      console.log(`    → Jira ${jiraKey}: pobieranie...`);
      jira = await getJiraIssue(jiraKey);

      if (jira) {
        console.log(`    → AI: przepisuję opis...`);
        jira.description = await rewriteDescription(jira.description, jira.summary);
      }
    }

    sections[entry.project].push({ ...entry, jiraKey, jira });
  }

  return { tag, sections, date: new Date().toLocaleDateString("pl-PL") };
}

// ─── Google Docs ──────────────────────────────────────────────────────────────

function buildSegments({ tag, sections, date }) {
  const segs = [];

  segs.push({ text: `Release Notes – ${tag}\n`, style: "HEADING_1" });
  segs.push({ text: `Data: ${date}\n\n`, italic: true });

  for (const proj of PROJECT_ORDER) {
    const items = sections[proj];
    if (!items?.length) continue;

    segs.push({ text: `${proj}:\n`, style: "HEADING_2" });

    for (const item of items) {
      const prLink = item.prNumber
        ? `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/pull/${item.prNumber}`
        : null;

      // Tytuł wpisu
      if (item.jira) {
        // Wpis z Jirą: "• RS-11221 – Tytuł zadania" jako link do Jiry
        const title = `${item.jiraKey} – ${item.jira.summary}`;
        segs.push({ text: "• " });
        segs.push({ text: title + "\n", bold: true, link: item.jira.url });
      } else if (prLink) {
        // Wpis bez Jiry: "• Opis zmiany, " + "#12394" jako link do PR
        segs.push({ text: "• " });
        segs.push({ text: item.description + ", ", bold: true });
        segs.push({ text: `#${item.prNumber}\n`, bold: true, link: prLink });
      } else {
        // Wpis bez Jiry i bez PR
        segs.push({ text: `• ${item.description}\n`, bold: true });
      }

      // Opis z Jiry (surowy)
      if (item.jira?.description) {
        segs.push({ text: item.jira.description + "\n", italic: true });
      }

      // Link do PR jeśli jest osobny od Jiry
      if (prLink && item.jira) {
        segs.push({ text: `PR #${item.prNumber}\n`, link: prLink, small: true });
      }

      segs.push({ text: "\n" });
    }
  }

  return segs;
}

async function updateGoogleDoc(data) {
  const auth = new google.auth.GoogleAuth({
    keyFile: GOOGLE_SA_KEY,
    scopes: ["https://www.googleapis.com/auth/documents"],
  });
  const docs = google.docs({ version: "v1", auth });

  // Pobierz aktualną długość dokumentu
  const doc = await docs.documents.get({ documentId: GOOGLE_DOC_ID });
  const endIdx = doc.data.body.content.at(-1).endIndex - 1;

  const requests = [];

  // Wyczyść obecną treść
  if (endIdx > 1) {
    requests.push({ deleteContentRange: { range: { startIndex: 1, endIndex: endIdx } } });
  }

  // Zbuduj segmenty tekstu
  const segs = buildSegments(data);
  const fullText = segs.map(s => s.text).join("");
  requests.push({ insertText: { location: { index: 1 }, text: fullText } });

  // Formatowanie segmentów
  let pos = 1;
  for (const seg of segs) {
    const len = seg.text.length;
    const end = pos + len;
    const range = { startIndex: pos, endIndex: end };

    if (seg.style) {
      requests.push({
        updateParagraphStyle: {
          range,
          paragraphStyle: { namedStyleType: seg.style },
          fields: "namedStyleType",
        },
      });
    }
    const textStyle = {};
    if (seg.bold)   textStyle.bold = true;
    if (seg.italic) textStyle.italic = true;
    if (seg.link)   textStyle.link = { url: seg.link };
    if (seg.small)  textStyle.fontSize = { magnitude: 9, unit: "PT" };

    if (Object.keys(textStyle).length) {
      requests.push({
        updateTextStyle: {
          range,
          textStyle,
          fields: Object.keys(textStyle).join(","),
        },
      });
    }

    pos = end;
  }

  await docs.documents.batchUpdate({
    documentId: GOOGLE_DOC_ID,
    requestBody: { requests },
  });

  console.log(`\n✅ Google Doc zaktualizowany!`);
  console.log(`   https://docs.google.com/document/d/${GOOGLE_DOC_ID}/edit`);
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export { buildReleaseNotes, updateGoogleDoc };

const isCLI = process.argv[1]?.endsWith('release-notes.mjs');
if (isCLI) {
  const tag = process.argv[2];
  if (!tag) {
    console.error("\n❌ Podaj tag jako argument.");
    console.error("   Przykład: node release-notes.mjs uat-version-20260316185950\n");
    process.exit(1);
  }
  buildReleaseNotes(tag)
    .then(updateGoogleDoc)
    .catch(err => {
      console.error("\n❌ Błąd:", err.message);
      process.exit(1);
    });
}